name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Der Job wir bei jedem Push in den Main Branch ausgefürt
        # Passe den Branch an, wenn nötig
  pull_request:
    branches:
      - main # Der Job wird ebenfalls bei jedem Pull Request in den Main Branch ausgeführt
  workflow_dispatch: # Ermöglicht manuelles Ausführen

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Erlaubt dass Images auf GHCR gepusht werden können mit "secrets.GITHUB_TOKEN"
      contents: read # Erlaubt den Zugriff auf die Repo mit "secrets.GITHUB_TOKEN"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
